version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - database
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: config/.env
    command: bundle exec ruby bin/main.rb
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  database:
    image: postgres:13.5
    environment:
      POSTGRES_PASSWORD: '123456'
    ports:
      - "7777:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:6.2
    ports:
      - "6379"
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "ping" ]
volumes:
  gem_cache:
  redis:
  db_data:

