development:
  clients:
    default:
      database: refueling_logger_development
      hosts:
        - mongo:27017
      options:
        server_selection_timeout: 1
production:
  clients:
    default:
      database: refueling_logger_production
      hosts:
        - mongo:27017
      options:
        server_selection_timeout: 1